Repository EmbarkStudios/rust-gpu, pull requests merged in 2020-11, with the labels that each got.

#184 Make all example windows 720p by default
  examples/runners/ash/src/main.rs
Labels: s: waiting on author

#199 Add enhancement issue template
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: s: waiting on review

#187 Add initial platform support docs
  docs/src/SUMMARY.md
  docs/src/platform-support.md
Labels: s: waiting on review

#195 Compute Shaders + ExecutionMode's
  Cargo.lock
  Cargo.toml
  crates/rustc_codegen_spirv/src/codegen_cx/declare.rs
  crates/rustc_codegen_spirv/src/codegen_cx/entry.rs
  crates/rustc_codegen_spirv/src/symbols.rs
  examples/runners/wgpu-compute/Cargo.toml
  examples/runners/wgpu-compute/build.rs
  examples/runners/wgpu-compute/src/main.rs
  examples/shaders/compute-shader/Cargo.toml
  examples/shaders/compute-shader/src/lib.rs
Labels: s: waiting on review

#212 Add changes to compile rust-gpu on the latest nightly
  crates/rustc_codegen_spirv/src/builder/mod.rs
  crates/rustc_codegen_spirv/src/codegen_cx/constant.rs
  crates/rustc_codegen_spirv/src/codegen_cx/mod.rs
  crates/rustc_codegen_spirv/src/lib.rs
  crates/spirv-builder/src/test/mod.rs
  crates/spirv-tools/src/opt/compiled.rs
  examples/runners/ash/src/main.rs
  rust-toolchain
Labels: s: waiting on review

#215 Add Android support to wgpu example
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  Cargo.lock
  docs/src/platform-support.md
  examples/runners/wgpu/Cargo.toml
  examples/runners/wgpu/src/lib.rs
  examples/runners/wgpu/src/main.rs
Labels: s: waiting on review

#222 Add trunc and fract to MathExt
  crates/spirv-std/src/math_ext.rs
Labels: c: spirv-std, t: enhancement, t: ergonomics

#248 Rename pow to powf, remove saturate from MathExt, and update to latest glam
  Cargo.lock
  crates/spirv-std/Cargo.toml
  crates/spirv-std/src/lib.rs
  crates/spirv-std/src/math_ext.rs
  examples/runners/cpu/Cargo.toml
  examples/runners/cpu/src/main.rs
  examples/shaders/shared/src/lib.rs
  examples/shaders/sky-shader/src/lib.rs
  setup.bat
  setup.sh
Labels: s: waiting on author

#275 Move lang_items into spirv-std
  crates/spirv-builder/src/test/mod.rs
  crates/spirv-std/src/lib.rs
  examples/shaders/compute-shader/src/lib.rs
  examples/shaders/simplest-shader/src/lib.rs
  examples/shaders/sky-shader/src/lib.rs
Labels: s: waiting on review
